# Generated by Django 4.2.13 on 2024-07-03 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите месторасположение оборудования', max_length=10, verbose_name='Месторасположение')),
            ],
        ),
        migrations.CreateModel(
            name='MethodNdt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите метод контроля', max_length=5, verbose_name='Метод контроля')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Введите статус оборудования', max_length=30, null=True, verbose_name='Статус оборудования')),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_manufacturer', models.CharField(blank=True, max_length=30, null=True, verbose_name='Производитель оборудования')),
                ('equipment_type', models.CharField(blank=True, max_length=30, null=True, verbose_name='Тип оборудования')),
                ('equipment_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Название оборудования')),
                ('equipment_serial_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Серийный номер')),
                ('total', models.IntegerField(verbose_name='Количество')),
                ('notes', models.CharField(blank=True, max_length=200, null=True, verbose_name='Примечание')),
                ('location', models.ForeignKey(help_text='Выберите месторасположение оборудования', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.location', verbose_name='Месторасположение')),
                ('method', models.ForeignKey(help_text='Выберите метод контроля', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.methodndt', verbose_name='Метод контроля')),
                ('status', models.ForeignKey(help_text='Выберите статус оборудования', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.status', verbose_name='Статус')),
            ],
        ),
    ]
