# Generated by Django 4.2.13 on 2024-07-07 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_manufacturer_type_remove_unit_equipment_manufacturer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturer',
            name='name',
            field=models.CharField(blank=True, help_text='Введите производителя оборудования', max_length=50, null=True, verbose_name='Производитель'),
        ),
        migrations.AlterField(
            model_name='methodndt',
            name='name',
            field=models.CharField(blank=True, help_text='Введите метод контроля', max_length=5, null=True, verbose_name='Метод контроля'),
        ),
        migrations.AlterField(
            model_name='type',
            name='name',
            field=models.CharField(blank=True, help_text='Введите тип оборудования', max_length=30, null=True, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='location',
            field=models.ForeignKey(help_text='Выберите месторасположение оборудования', on_delete=django.db.models.deletion.CASCADE, to='catalog.location', verbose_name='Месторасположение'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='manufacturer',
            field=models.ForeignKey(max_length=30, on_delete=django.db.models.deletion.CASCADE, to='catalog.manufacturer', verbose_name='Производитель оборудования'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='method',
            field=models.ForeignKey(help_text='Выберите метод контроля', on_delete=django.db.models.deletion.CASCADE, to='catalog.methodndt', verbose_name='Метод контроля'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='status',
            field=models.ForeignKey(help_text='Выберите статус оборудования', on_delete=django.db.models.deletion.CASCADE, to='catalog.status', verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='type',
            field=models.ForeignKey(max_length=30, on_delete=django.db.models.deletion.CASCADE, to='catalog.type', verbose_name='Тип оборудования'),
        ),
    ]
