# Generated by Django 4.2.13 on 2024-07-07 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_manufacturer_name_alter_methodndt_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='notes',
            field=models.CharField(max_length=200, verbose_name='Примечание'),
        ),
    ]
